
version: "3.9"

services:
  database_seidor:
    image: postgres
    container_name: database_seidor
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=seidor
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: seidor
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_seidor
    depends_on:
      - database_seidor



volumes:
  pgdata:
    driver: local